vich_uploader:
    db_driver: orm
    mappings:
        plante_images:
            uri_prefix: '%plante_images%'
            upload_destination: '%kernel.project_dir%/public%plante_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer